import {
  Organization,
  Category,
  Product,
  Service,
  PaymentAccount,
  ExpenseCategory,
  Customer,
} from '../types';

export const DEFAULT_ORGANIZATION: Organization = {
  id: 'org-yaqoob-001',
  name: 'Yaqoob Enterprises',
  owner_name: 'Muhammad Yaqoob',
  currency: 'PKR',
  currency_symbol: 'Rs.',
  country: 'Pakistan',
  timezone: 'Asia/Karachi',
  business_category: 'Photocopy, Printing, Stationery & Public Facilitation',
  phone: '+92 300 1234567',
  email: 'yaqoobenterprisesofficial@gmail.com',
  address: 'Shop # 4, Main Commercial Market, Near Kutchery Road',
  tax_rate: 0,
  tax_enabled: false,
  receipt_footer: 'Thank you for choosing Yaqoob Enterprises! Quality service is our motto.',
  invoice_prefix: 'YE-',
  next_invoice_number: 1042,
  created_at: new Date().toISOString(),
};

export const STARTER_CATEGORIES: Category[] = [
  {
    id: 'cat-services',
    organization_id: 'org-yaqoob-001',
    name: 'Printing & Copy Services',
    type: 'SERVICE',
    color: '#06B6D4',
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-documentation',
    organization_id: 'org-yaqoob-001',
    name: 'Legal & Documentation',
    type: 'SERVICE',
    color: '#3B82F6',
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-facilitation',
    organization_id: 'org-yaqoob-001',
    name: 'Online & Ticketing',
    type: 'SERVICE',
    color: '#8B5CF6',
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-stationery',
    organization_id: 'org-yaqoob-001',
    name: 'Office Stationery',
    type: 'PRODUCT',
    color: '#10B981',
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-paper',
    organization_id: 'org-yaqoob-001',
    name: 'Paper & Raw Materials',
    type: 'PRODUCT',
    color: '#F59E0B',
    created_at: new Date().toISOString(),
  },
];

export const STARTER_PRODUCTS: Product[] = [
  {
    id: 'prod-a4-sheet',
    organization_id: 'org-yaqoob-001',
    name: 'A4 70gsm Copy Paper (Single Sheet)',
    sku: 'PPR-A4-SHT',
    category_id: 'cat-paper',
    category_name: 'Paper & Raw Materials',
    unit: 'Sheet',
    purchase_price: 2.2,
    selling_price: 5.0,
    opening_stock: 4500,
    current_stock: 4320,
    min_stock_threshold: 500,
    track_stock: true,
    is_active: true,
    supplier: 'Al-Madina Paper Mart',
    average_cost: 2.2,
    stock_value: 9504,
    notes: 'Used for B&W copying and laser printing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-a4-color-sheet',
    organization_id: 'org-yaqoob-001',
    name: 'A4 80gsm Premium Gloss/Bright Sheet',
    sku: 'PPR-A4-80G',
    category_id: 'cat-paper',
    category_name: 'Paper & Raw Materials',
    unit: 'Sheet',
    purchase_price: 4.5,
    selling_price: 10.0,
    opening_stock: 1200,
    current_stock: 980,
    min_stock_threshold: 200,
    track_stock: true,
    is_active: true,
    supplier: 'Al-Madina Paper Mart',
    average_cost: 4.5,
    stock_value: 4410,
    notes: 'Used for Colour prints and certificates',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-photo-sheet',
    organization_id: 'org-yaqoob-001',
    name: 'RC Glossy Photo Paper 4x6',
    sku: 'PPR-PHT-4X6',
    category_id: 'cat-paper',
    category_name: 'Paper & Raw Materials',
    unit: 'Sheet',
    purchase_price: 12.0,
    selling_price: 30.0,
    opening_stock: 300,
    current_stock: 240,
    min_stock_threshold: 50,
    track_stock: true,
    is_active: true,
    supplier: 'Fujifilm / Kodak Distributor',
    average_cost: 12.0,
    stock_value: 2880,
    notes: 'For passport size photo 8-pack prints',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-a4-rim',
    organization_id: 'org-yaqoob-001',
    name: 'A4 70gsm Paper Rim (500 Sheets)',
    sku: 'PPR-A4-RIM',
    category_id: 'cat-stationery',
    category_name: 'Office Stationery',
    unit: 'Rim',
    purchase_price: 1050.0,
    selling_price: 1250.0,
    opening_stock: 25,
    current_stock: 18,
    min_stock_threshold: 5,
    track_stock: true,
    is_active: true,
    supplier: 'JK Paper Traders',
    average_cost: 1050.0,
    stock_value: 18900,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-legal-rim',
    organization_id: 'org-yaqoob-001',
    name: 'Legal 75gsm Paper Rim (500 Sheets)',
    sku: 'PPR-LGL-RIM',
    category_id: 'cat-stationery',
    category_name: 'Office Stationery',
    unit: 'Rim',
    purchase_price: 1250.0,
    selling_price: 1480.0,
    opening_stock: 15,
    current_stock: 9,
    min_stock_threshold: 3,
    track_stock: true,
    is_active: true,
    supplier: 'JK Paper Traders',
    average_cost: 1250.0,
    stock_value: 11250,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-box-file',
    organization_id: 'org-yaqoob-001',
    name: 'Executive Box File Legal Size',
    sku: 'STN-FLE-BX',
    category_id: 'cat-stationery',
    category_name: 'Office Stationery',
    unit: 'Pcs',
    purchase_price: 140.0,
    selling_price: 220.0,
    opening_stock: 60,
    current_stock: 42,
    min_stock_threshold: 10,
    track_stock: true,
    is_active: true,
    supplier: 'Crown Stationery',
    average_cost: 140.0,
    stock_value: 5880,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-ballpen-box',
    organization_id: 'org-yaqoob-001',
    name: 'Dollar Clipper Ball Pen 0.7mm (Box of 10)',
    sku: 'STN-PEN-BX',
    category_id: 'cat-stationery',
    category_name: 'Office Stationery',
    unit: 'Box',
    purchase_price: 220.0,
    selling_price: 320.0,
    opening_stock: 40,
    current_stock: 31,
    min_stock_threshold: 8,
    track_stock: true,
    is_active: true,
    supplier: 'National Stationery Wholesale',
    average_cost: 220.0,
    stock_value: 6820,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-khaki-envelope',
    organization_id: 'org-yaqoob-001',
    name: 'Legal Khaki Cloth-Lined Document Envelope',
    sku: 'STN-ENV-LGL',
    category_id: 'cat-stationery',
    category_name: 'Office Stationery',
    unit: 'Pcs',
    purchase_price: 15.0,
    selling_price: 30.0,
    opening_stock: 200,
    current_stock: 145,
    min_stock_threshold: 30,
    track_stock: true,
    is_active: true,
    supplier: 'Al-Madina Paper Mart',
    average_cost: 15.0,
    stock_value: 2175,
    created_at: new Date().toISOString(),
  },
];

export const STARTER_SERVICES: Service[] = [
  {
    id: 'srv-bw-copy',
    organization_id: 'org-yaqoob-001',
    name: 'B&W Photocopy (A4 / Single Sided)',
    sku: 'SRV-CPY-BW',
    category_id: 'cat-services',
    category_name: 'Printing & Copy Services',
    selling_price: 10.0,
    estimated_cost: 2.2,
    is_active: true,
    notes: 'Fast dual scan xerox copy',
    components: [
      {
        id: 'rec-1',
        organization_id: 'org-yaqoob-001',
        service_id: 'srv-bw-copy',
        product_id: 'prod-a4-sheet',
        product_name: 'A4 70gsm Copy Paper (Single Sheet)',
        quantity_consumed: 1,
        unit: 'Sheet',
      },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-color-copy',
    organization_id: 'org-yaqoob-001',
    name: 'Colour Photocopy / Scan (A4)',
    sku: 'SRV-CPY-CLR',
    category_id: 'cat-services',
    category_name: 'Printing & Copy Services',
    selling_price: 35.0,
    estimated_cost: 4.5,
    is_active: true,
    notes: 'High resolution digital color reproduction',
    components: [
      {
        id: 'rec-2',
        organization_id: 'org-yaqoob-001',
        service_id: 'srv-color-copy',
        product_id: 'prod-a4-color-sheet',
        product_name: 'A4 80gsm Premium Gloss/Bright Sheet',
        quantity_consumed: 1,
        unit: 'Sheet',
      },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-bw-print',
    organization_id: 'org-yaqoob-001',
    name: 'B&W Laser Printing (A4)',
    sku: 'SRV-PRT-BW',
    category_id: 'cat-services',
    category_name: 'Printing & Copy Services',
    selling_price: 15.0,
    estimated_cost: 2.2,
    is_active: true,
    notes: 'Direct from USB / WhatsApp / Email',
    components: [
      {
        id: 'rec-3',
        organization_id: 'org-yaqoob-001',
        service_id: 'srv-bw-print',
        product_id: 'prod-a4-sheet',
        product_name: 'A4 70gsm Copy Paper (Single Sheet)',
        quantity_consumed: 1,
        unit: 'Sheet',
      },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-color-print',
    organization_id: 'org-yaqoob-001',
    name: 'Colour High-Res Laser Print (A4)',
    sku: 'SRV-PRT-CLR',
    category_id: 'cat-services',
    category_name: 'Printing & Copy Services',
    selling_price: 50.0,
    estimated_cost: 4.5,
    is_active: true,
    notes: 'For documents, cards, presentations',
    components: [
      {
        id: 'rec-4',
        organization_id: 'org-yaqoob-001',
        service_id: 'srv-color-print',
        product_id: 'prod-a4-color-sheet',
        product_name: 'A4 80gsm Premium Gloss/Bright Sheet',
        quantity_consumed: 1,
        unit: 'Sheet',
      },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-passport-photo',
    organization_id: 'org-yaqoob-001',
    name: 'Passport Photos (8 Copies with Blue/White BG)',
    sku: 'SRV-PHT-PSS',
    category_id: 'cat-services',
    category_name: 'Printing & Copy Services',
    selling_price: 250.0,
    estimated_cost: 12.0,
    is_active: true,
    notes: 'Studio camera click, background retouching, printed in 5 mins',
    components: [
      {
        id: 'rec-5',
        organization_id: 'org-yaqoob-001',
        service_id: 'srv-passport-photo',
        product_id: 'prod-photo-sheet',
        product_name: 'RC Glossy Photo Paper 4x6',
        quantity_consumed: 1,
        unit: 'Sheet',
      },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-typing',
    organization_id: 'org-yaqoob-001',
    name: 'Urdu / English Typing (Per Page)',
    sku: 'SRV-DOC-TYP',
    category_id: 'cat-documentation',
    category_name: 'Legal & Documentation',
    selling_price: 150.0,
    estimated_cost: 0,
    is_active: true,
    notes: 'Applications, letters, resumes, statements',
    components: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-stamp-paper',
    organization_id: 'org-yaqoob-001',
    name: 'Stamp Paper / Affidavit / Agreement Formatting & Print',
    sku: 'SRV-DOC-STP',
    category_id: 'cat-documentation',
    category_name: 'Legal & Documentation',
    selling_price: 350.0,
    estimated_cost: 0,
    is_active: true,
    notes: 'Rental agreements, declarations, undertakings, e-stamp verification',
    components: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-online-forms',
    organization_id: 'org-yaqoob-001',
    name: 'Online Government / Job Application Submission',
    sku: 'SRV-FAC-JOB',
    category_id: 'cat-facilitation',
    category_name: 'Online & Ticketing',
    selling_price: 200.0,
    estimated_cost: 0,
    is_active: true,
    notes: 'PPSC, FPSC, NTS, University admissions, passport token',
    components: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-biometric',
    organization_id: 'org-yaqoob-001',
    name: 'Biometric Verification / NADRA / E-Sahulat Service',
    sku: 'SRV-FAC-BIO',
    category_id: 'cat-facilitation',
    category_name: 'Online & Ticketing',
    selling_price: 100.0,
    estimated_cost: 0,
    is_active: true,
    notes: 'SIM verification, pension verification, citizen portal',
    components: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-ticket-booking',
    organization_id: 'org-yaqoob-001',
    name: 'Train / Daewoo Bus / Air Ticket Booking Service Fee',
    sku: 'SRV-FAC-TCK',
    category_id: 'cat-facilitation',
    category_name: 'Online & Ticketing',
    selling_price: 300.0,
    estimated_cost: 0,
    is_active: true,
    notes: 'Pakistan Railways, Faisal Movers, PIA booking assistance',
    components: [],
    created_at: new Date().toISOString(),
  },
];

export const STARTER_PAYMENT_ACCOUNTS: PaymentAccount[] = [
  {
    id: 'acc-cash',
    organization_id: 'org-yaqoob-001',
    name: 'Cash Drawer',
    type: 'CASH',
    current_balance: 18450.0,
    opening_balance: 10000.0,
    is_active: true,
    is_default: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'acc-hbl',
    organization_id: 'org-yaqoob-001',
    name: 'HBL Business Account',
    type: 'BANK',
    account_number: '0129-7901-4451-03',
    current_balance: 64200.0,
    opening_balance: 50000.0,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'acc-jazzcash',
    organization_id: 'org-yaqoob-001',
    name: 'JazzCash Merchant Till',
    type: 'DIGITAL_WALLET',
    account_number: '0300-1234567',
    current_balance: 14850.0,
    opening_balance: 5000.0,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'acc-easypaisa',
    organization_id: 'org-yaqoob-001',
    name: 'Easypaisa Business',
    type: 'DIGITAL_WALLET',
    account_number: '0345-9876543',
    current_balance: 9300.0,
    opening_balance: 4000.0,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const STARTER_EXPENSE_CATEGORIES: ExpenseCategory[] = [
  {
    id: 'exp-cat-rent',
    organization_id: 'org-yaqoob-001',
    name: 'Shop Rent',
    description: 'Monthly commercial shop rental',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-cat-power',
    organization_id: 'org-yaqoob-001',
    name: 'Electricity & Generator Fuel',
    description: 'WAPDA bill and generator petrol/diesel expenses',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-cat-salary',
    organization_id: 'org-yaqoob-001',
    name: 'Staff Salary & Daily Wages',
    description: 'Computer operators and shop assistants',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-cat-maint',
    organization_id: 'org-yaqoob-001',
    name: 'Photocopier Toner & Machine Maintenance',
    description: 'Drum unit replacement, developer, laser servicing',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-cat-internet',
    organization_id: 'org-yaqoob-001',
    name: 'Fiber Internet & Phone',
    description: 'High-speed broadband connection',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-cat-tea',
    organization_id: 'org-yaqoob-001',
    name: 'Office Tea & Customer Refreshment',
    description: 'Daily hospitality and drinking water',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const STARTER_CUSTOMERS: Customer[] = [
  {
    id: 'cust-walkin',
    organization_id: 'org-yaqoob-001',
    name: 'Walk-in Customer (General Public)',
    phone: '',
    email: '',
    address: 'Counter sale',
    notes: 'Default walk-in retail buyer',
    total_purchases: 48200,
    last_purchase_date: new Date().toISOString(),
    outstanding_balance: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cust-tariq',
    organization_id: 'org-yaqoob-001',
    name: 'Advocate Tariq Mahmood (Kutchery Chamber)',
    phone: '+92 321 8844221',
    email: 'tariq.legal@gmail.com',
    address: 'Chamber # 12, District Courts',
    notes: 'Regular legal draft and stamp paper client',
    total_purchases: 18500,
    last_purchase_date: new Date().toISOString(),
    outstanding_balance: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cust-school',
    organization_id: 'org-yaqoob-001',
    name: 'The Educators High School (Admin Office)',
    phone: '+92 333 5511223',
    email: 'admin.educators@school.edu',
    address: 'Civil Lines, Near Yaqoob Market',
    notes: 'Exam papers, syllabus copying, registers',
    total_purchases: 45000,
    last_purchase_date: new Date().toISOString(),
    outstanding_balance: 1500,
    created_at: new Date().toISOString(),
  },
];
